fpn/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('main.urls')),
    path('', include('detail.urls')),
]

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .managers import CustomUserManager
from fpn import commons


class Office(models.Model):
    """used as users identifier in the system"""
    
    created_at = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=255, unique=True)
    address = models.CharField(max_length=255)
    email = models.EmailField(blank=True, unique=True)
    contact_no = models.CharField(max_length=15, blank=True)
    contact_person = models.CharField(max_length=255, blank=True)
    category = models.CharField(max_length=255, choices=commons.OFFICE_CHOICES)
    working_area = models.CharField(max_length=255)
    
    def office_name(self):
        return f"{self.name}, {self.address}"
    
    def __str__(self):
        return self.office_name()


class CustomUser(AbstractUser):
    """defining our model for custom users"""
    
    office = models.ForeignKey(Office, on_delete=models.CASCADE, related_name='users', null=True, blank=True)
    username = models.CharField(max_length=255, unique=True)
    name = models.CharField(max_length=255)
    email = models.EmailField(unique=True)
    phone_number = models.CharField(max_length=255)
    role = models.CharField(max_length=255, choices=commons.ROLE_CHOICES)
    department_category = models.CharField(max_length=255, choices=commons.DEPARTMENT_CHOICES, blank=True)
    
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []
    
    objects = CustomUserManager()
    
    def __str__(self):
        return self.email
    
    

templates/user/changepassword.html
{% extends 'base/base.html' %}
{% load static %}
{% block container %}
    
    <div class="add-heading">
        <h3 class="heading-cm">
            <a href="" class="nav-icon me-2">
                <i class="fa-solid fa-angle-left"></i>
            </a>
            My Profile<span class="sub-nav ms-2"> > {{user_object.name}} > Change Password</span>
        </h3>
    </div>

    {% for message in messages %}
        {% if message.tags == "success" %}
            <div class="alert alert-success">{{ message }}</div>
        {% elif message.tags == "error" %}
            <div class="alert alert-danger">{{ message }}</div>
        {% endif %}
    {% endfor %}

    <div class="form-cm">
        <form method="POST" action="" class="entry-form ">
            {% csrf_token %}
            <div class="row mb-3">
                <div class="col-md-12">
                    <label for="" class="form-label cm">Current Password</label>
                    <input type="password" class="form-control cm ps-2"
                        placeholder="Enter your current password" name="current_password" required>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <label for="" class="form-label cm">New Password</label>
                    <input placeholder="Enter new password" id="password" type="password"
                        class="form-control cm" name="new_password" required>
                </div>
                <div class="col-md-6"> <label for="" class="form-label cm">Confirm New Password</label>
                    <input name="new_password_confirmation" placeholder="Enter confirm password" type="password"
                        class="form-control cm"
                        autocomplete="new_password" required>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 text-end"> 
                    <button type="submit" class="btn btn-primary mt-2 w-25">Change Password</button>
                </div>
            </div>
        </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.2/moment.min.js"></script>
    <script src="https://cdn.datatables.net/datetime/1.4.1/js/dataTables.dateTime.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.print.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>

    <script src="../datepicker/nepali-date-picker.min.js"></script>
    <script src="../../js/script.js"></script>
    <script>
        $(document).ready(function () {
            $('.mySelect').select2({
                placeholder: 'Select'
            });
        });

        $(document).ready(function () {
            $('.multipleselect').select2({
                closeOnSelect: false,
                placeholder: 'Select'
            });
        });


        $(document).ready(function () {
            var successAlert = $(".alert");

            if (successAlert.length > 0) {
                setTimeout(function () {
                    successAlert.alert('close');
                }, 5000);
            }
        });

        jQuery(document).ready(function() {
            $('.date-picker').nepaliDatePicker();
        })



        function previewImages(event) {
        var previewContainer = document.getElementById('previewContainer');
        previewContainer.innerHTML = '';
        var files = event.target.files;
        for (var i = 0; i < files.length; i++) {
            var file = files[i];
            var reader = new FileReader();
            reader.onload = function (e) {
                var image = document.createElement('img');
                image.src = e.target.result;
                image.classList.add('previewImage');
                previewContainer.appendChild(image);
            };
            reader.readAsDataURL(file);
        }
    }





    $('#select_box').change(function () {
        var select1 = $(this).find(':selected').val();
        $(".hide").hide();
        $('#' + select1).show();
    }).change()

    $('#office-selection').change(function () {
        var select2 = $(this).find(':selected').val();
        $(".hide").hide();
        if(select2==5){
            $("#1").show();
            $('#import-export').show();
        }else if(select2==6){
            $("#1").show();
            $('#division-office').show();
        }else if(select2==7){
            $("#1").show();
            $('#food-office').show();
        }else if(select2==8 || select2==9 || select2==10 || select2==11){
            $("#1").show();
        }
    }).change()











    </script>

{% endblock %}

templates/user/forgetpassword.html
{% load static %}
<!doctype html>
<html>

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Food Project</title>
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
            crossorigin="anonymous">
        <link rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
            integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
            crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet"
            href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.css" />
        <link rel="stylesheet"
            href="https://cdn.datatables.net/datetime/1.4.1/css/dataTables.dateTime.min.css">
        <link
            href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css"
            rel="stylesheet" />
        <link rel="stylesheet"
            href="https://cdn.datatables.net/buttons/2.3.6/css/buttons.dataTables.min.css">
        <link rel="stylesheet"
            href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <link
            href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css"
            rel="stylesheet" />
        <link rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

        <link rel="shortcut icon" href="../../image/np.png" type="image/x-icon">

        <link rel="stylesheet" href="{% static '/css/style.css' %}">
        <link rel="stylesheet" href="../datepicker/nepali-date-picker.min.css">

    </head>

    <body>

        <div class="container">
            <div class="row login-row">
                <div class="form-heading-top mb-1">
                    <img src="{% static '/image/np.png' %}" alt="">
                    <p class="mt-2">Department of Food Technology and Quality Control<br>
                        <span> Babarmahal,Kathmandu</span>
                    </p>
                </div>

            {% for message in messages %}
                {% if message.tags == "success" %}
                    <div class="alert alert-success">{{ message }}</div>
                {% elif message.tags == "error" %}
                    <div class="alert alert-danger">{{ message }}</div>
                {% endif %}
            {% endfor %}

                <form method="POST" action="" class="entry-form login-form">
                    {% csrf_token %}
                    <div class="row fst-row mb-2">
                        <h3>Reset Password</h3>
                        <p>Please enter your email address.</p>
                    </div>
                    <div class="row">
                        <label for="" class="form-label cm">Email Address</label>
                        <div class="input-container">
                            <img class="login-icon-left" src="{% static '/image/user.svg' %}" alt="">
                            <input id="email" type="email" class="form-control cm"
                                name="email" required autocomplete="email" autofocus
                                autocomplete="email" autofocus aria-describedby="emailHelp"
                                placeholder="Enter your email address" name="email" required>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary w-100 mt-3">Send Password Reset Link</button>
                </form>
            </div>
        </div>

        <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js"
            integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE"
            crossorigin="anonymous">
        </script>
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
            crossorigin="anonymous">
        </script>

        <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
        <script
            src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
        <script
            src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.2/moment.min.js"></script>
        <script
            src="https://cdn.datatables.net/datetime/1.4.1/js/dataTables.dateTime.min.js"></script>
        <script
            src="https://cdn.datatables.net/buttons/2.3.6/js/dataTables.buttons.min.js"></script>
        <script
            src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
        <script
            src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
        <script
            src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
        <script
            src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.html5.min.js"></script>
        <script
            src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.print.min.js"></script>
        <script
            src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>

    </body>

</html>

templates/user/resetpassword.html
{% load static %}
<!doctype html>
<html>

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Food Project</title>
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
            crossorigin="anonymous">
        <link rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
            integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
            crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet"
            href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.css" />
        <link rel="stylesheet"
            href="https://cdn.datatables.net/datetime/1.4.1/css/dataTables.dateTime.min.css">
        <link
            href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css"
            rel="stylesheet" />
        <link rel="stylesheet"
            href="https://cdn.datatables.net/buttons/2.3.6/css/buttons.dataTables.min.css">
        <link rel="stylesheet"
            href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <link
            href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css"
            rel="stylesheet" />
        <link rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

        <link rel="shortcut icon" href="../../image/np.png" type="image/x-icon">

        <link rel="stylesheet" href="{% static '/css/style.css' %}">
        <link rel="stylesheet" href="../datepicker/nepali-date-picker.min.css">

    </head>

    <body>

        <div class="container">
            <div class="row login-row" style="width: 800px;">
                <div class="form-heading-top mb-1">
                    <img src="{% static '/image/np.png' %}" alt="">
                    <p class="mt-2">Department of Food Technology and Quality Control<br>
                        <span> Babarmahal,Kathmandu</span>
                    </p>
                </div>

                
                {% if validlink %}
                <form action="" method="post" class="user-form-main">
                    {% csrf_token %}

                    <div class="  form-bdr ">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="row">
                                    <label for="exampleInputFullName" class="form-label">New Password</label>

                                    <div class="input-container">
                                        <img class="login-icon-left" src="{% static '/image/lock-alt.svg' %}" alt="">
    
                                        <input type="password" class="form-control" id="exampleInputEmail1"
                                            aria-describedby="passwordHelp" placeholder="Enter your Password" name="new_password1">
                                    </div>
    
                                </div>
                                <div class="row">
                                    <label for="exampleInputFullName" class="form-label">New Password Confirmation</label>
    
    
                                    <div class="input-container">
                                        <img class="login-icon-left" src="{% static '/image/lock-alt.svg' %}" alt="">
    
                                        <input type="password" class="form-control" id="exampleInputEmail1"
                                            aria-describedby="passwordHelp" placeholder="Enter your Password" name="new_password2">
                                    </div>
    
                                </div>
                                <div class="row">
                                    <div class="input-container">
                                        <button type="submit" class="btn btn-primary w-100">Submit</button>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="col-lg-12 user-side-view">
                                    <h5>Instructions for password</h5>
                                    <ul>
                                        <li>Your password can't be too similar to your other personal information.</li>
                                        <li>Your password must contain at least 8 characters.</li>
                                        <li>Your password can't be a commonly used password.</li>
                                        <li>Your password can't be entirely numeric.</li>
                                    </ul>
                                </div>
                            </div>
                            
                        </div>
                    </div>

                    

                </form>
                {% else %}
                <p style="text-center">The password reset link was invalid, possibly because it has
                already been used. Please request a new password reset.</p>
                <a href="{% url 'login' %}"><button class="btn btn-primary">Go Back</button></a>
                {% endif %}

            </div>
        </div>

        <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js"
            integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE"
            crossorigin="anonymous">
        </script>
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
            crossorigin="anonymous">
        </script>

        <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
        <script
            src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
        <script
            src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.2/moment.min.js"></script>
        <script
            src="https://cdn.datatables.net/datetime/1.4.1/js/dataTables.dateTime.min.js"></script>
        <script
            src="https://cdn.datatables.net/buttons/2.3.6/js/dataTables.buttons.min.js"></script>
        <script
            src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
        <script
            src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
        <script
            src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
        <script
            src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.html5.min.js"></script>
        <script
            src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.print.min.js"></script>
        <script
            src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>

    </body>

</html>

templates/user/userdisplay.html
{% extends 'base/base.html' %}
{% load static %}
{% block container %}
    <div class="add-heading">
        <h3 class="heading-cm">
            <a href="" class="nav-icon me-2">
                <i class="fa-solid fa-angle-left"></i>
            </a>
            User<span class="sub-nav ms-2"> > All</span>
        </h3>
        <p><a href=""><i class="fa-regular fa-eye"></i>View Users</a></p>
    </div>

    {% for message in messages %}
        {% if message.tags == "success" %}
            <div class="alert alert-success">{{ message }}</div>
        {% elif message.tags == "error" %}
            <div class="alert alert-danger">{{ message }}</div>
        {% elif message.tags == "info" %}
            <div class="alert alert-warning">{{ message }}</div>
        {% endif %}
    {% endfor %}

    <div class="table-row">
        <div class="row mb-4 filter-row filters">
            <div class="col-md-4">
                <select id="role" class="form-select kit-form-control">
                    <option value="" disabled selected>Select Role</option>
                    <option value="Data Entry Operator">Data Entry Operator</option>
                    <option value="Report Viewer">Verifier</option>
                    <option value="Report Viewer">Admin</option>
                </select>
            </div>
            <div class="col-md-3">
                <input type="text" class="form-control cm" id="min" name="min" placeholder="From">
            </div>
            <div class="col-md-3">
                <input type="text" class="form-control cm" id="max" name="max" placeholder="To">
            </div>
            <div class="col-md-2">
                <button id="reset">Reset</button>
            </div>
        </div>
    
        <table id="sampleTable" class="table table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>S No.</th>
                    <th>User Name</th>
                    <th>Email Address</th>
                    <th>Role</th>
                    <th>Department</th>
                    <th>Office</th>
                    <th>Created Date</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for u in users %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{u.username}}</td>
                    <td>{{u.email}}</td>
                    <td>{{u.get_role_display}}</td>
                    <td>{{u.get_department_category_display}}</td>
                    <td>{{u.office.office_name}}</td>
                    <td>{{u.date_joined|date:"Y-m-d"}}</td>
    
                    <td>
                        <div class="d-flex kit-action-com">
                            <div class="action-btn-pen">
                            <a href="{% url 'user-edit' id=u.id %}" method="put"><span class="material-symbols-outlined">
                                    edit
                                    </span></a>
                            </div>
    
                            <form class="action-btn-dlt" action="{% url 'user-delete' id=u.id %}" method="post">
                                {% csrf_token %}
                                <button type="submit">
                                    <i class="fa-regular fa-trash-can"></i>
                                </button>
                            </form>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}





    

templates/user/useredit.html
{% extends 'base/base.html' %}
{% load static %}
{% block container %}
    <div class="add-heading">
        <h3 class="heading-cm">
            <a href="" class="nav-icon me-2">
                <i class="fa-solid fa-angle-left"></i>
            </a>
            User<span class="sub-nav ms-2"> > Update</span>
        </h3>
        <p><a href=""><i class="fa-regular fa-eye"></i>Update User Details</a></p>
    </div>

    {% for message in messages %}
        {% if message.tags == "error" %}
            <div class="alert alert-danger">{{ message }}</div>
        {% elif message.tags == "info" %}
            <div class="alert alert-warning">{{ message }}</div>
        {% endif %}
    {% endfor %}

    <form action="" method="POST" class="form-cm" enctype="multipart/form-data"
        id="myForm">
        {% csrf_token %}
        <div class="col-md-12">
            <h3 class="create-form-heading">Update User</h3>
        </div>

        <div class="row mb-2">
            <div class="mb-3 col-md-6">
                <label for="" class="form-label cm">Full Name</label>
                <input type="text" class="form-control cm" placeholder="Enter full name" name="name" value="{{user_object.name}}" required>
            </div>

            <div class="mb-3 col-md-6">
                <label for="" class="form-label cm">Username</label>
                <input type="text" class="form-control cm" placeholder="Enter username" name="username" value="{{user_object.username}}" required>
            </div>
        </div>

        <div class="row mb-2">
            <div class="mb-3 col-md-6">
                <label for="" class="form-label cm">Email address</label>
                <input type="email" class="form-control cm" placeholder="Enter email address" name="email" value="{{user_object.email}}" required>
            </div>

            <div class="mb-3 col-md-6">
                <label for="" class="form-label cm">Phone Number</label>
                <input type="text" class="form-control cm" placeholder="Enter phone number" name="phone_number" value="{{user_object.phone_number}}" required>
            </div>
        </div>
    
        <div class="row mt-3">
            <div class="col-md-12 text-end"><button type="submit" name="verify" class="btn btn-primary">Update User</button></div>
        </div>

    </form> 
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script>
    
    $('#office-selection').change(function () {
        var select2 = $(this).find(':selected').val();

        $(".hide").hide();
        if(select2=='IE'){
            $('#DE').show();
            $('#import-export').show();
        }else if(select2=="DO"){
            $("#DE").show();
            $('#division-office').show();
        }else if(select2=="FO"){
            $("#DE").show();
            $('#food-office').show();
        }else if(select2=="FFSQRD" || select2=="FTDND" || select2=="NFFRL" || select2=="A"){
            $("#DE").show();
        }
    }).change();


    $('#select_box').change(function () {
        var select1 = $(this).find(':selected').val();
        console.log(select1)
        $(".hide").hide();
        $('#' + select1).show();
    }).change();

</script>
{% endblock %}
    

templates/user/userprofile.html
{% extends 'base/base.html' %}
{% load static %}
{% block container %}
    <div class="add-heading">
        <h3 class="heading-cm">
            <a href="" class="nav-icon me-2">
                <i class="fa-solid fa-angle-left"></i>
            </a>
            My Profile<span class="sub-nav ms-2"> > {{user.name}}</span>
        </h3>
    </div>

    {% for message in messages %}
        <div class="alert alert-success">{{ message }}</div>
    {% endfor %}

    <div class="form-cm">
        <div class="row userprofile-das">
            <div class="col-md-6 userprofile-das-left">
                <div class="me-3 userprofile-das-div"> <img
                        src="https://ui-avatars.com/api/?name=Pradeep+Marasini&rounded=true&background=FB802C&color=ffffff&size=28&bold=true"
                        alt=""></div>

                <div class="userprofile-text">
                    <h3 class="username">{{user.username}}</h3>
                    <p class="username-sm"> Role : <span>{{user.get_role_display}}</span> </p>
                </div>
            </div>
            <div class="col-md-6 userprofile-das-right">
                <a href="{% url 'user-edit' id=user.id %}">Edit Details</a>
                <a href="{% url 'password-change' id=user.id %}">Change Password</a>
            </div>
        </div>
        <div class="row userprofile-details">
            <div class="userdetails-heading">
                User Details
            </div>
            <div class="col-md-3">
                <h3>Full Name</h3>
                <p>{{user.name}}</p>
            </div>
            <div class="col-md-3">
                <h3>Username</h3>
                <p>{{user.username}}</p>
            </div>
            <div class="col-md-3">
                <h3>Phone Number</h3>
                <p>{{user.phone_number}}</p>
            </div>
            <div class="col-md-3">
                <h3>Email</h3>
                <p>{{user.email}}</p>
            </div>
        </div>
        <div class="row userprofile-details">
            <div class="col-md-3">
                <h3>Department Name</h3>
                <p>{{user.get_department_category_display}}</p>
            </div>
            <div class="col-md-3">
                <h3>Office Name</h3>
                <p>{{user.office.name}}</p>
            </div>
            <div class="col-md-3">
                <h3>Office Address</h3>
                <p>{{user.office.address}}</p>
            </div>
            <div class="col-md-3">
                <h3>Office Contact Number</h3>
                <p>{{user.office.contact_no}}</p>
            </div>
        </div>
    </div>
{% endblock %}