fpn/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('main.urls')),
    path('', include('detail.urls')),
]

main/models.py
from django.db import models
from fpn import commons
from fpn.model_mixins import FPNBaseModel
from account.models import CustomUser
from .validators import validate_nepali_date
from .managers import ObjectManager,QuarterelyMonthlyBudgetObjectManager,YearlyBudgetObjectManager


class AarthikBarsa(models.Model):
    aarthik_barsa=models.CharField(max_length=12)

class BarsikLakshya(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="users")
    namuna_bibaran = models.PositiveIntegerField(default=0, blank=True)
    anugaman = models.PositiveIntegerField(default=0, blank=True)
    logo = models.PositiveIntegerField(default=0, blank=True)
    namuna_bisleysan = models.PositiveIntegerField(default=0, blank=True)
    prayogsala = models.PositiveIntegerField(default=0, blank=True)
    patrajari = models.PositiveIntegerField(default=0, blank=True)
    patranabikaran = models.PositiveIntegerField(default=0, blank=True)
    udyog_sifaris = models.PositiveIntegerField(default=0, blank=True)
    aayat_niryat = models.PositiveIntegerField(default=0, blank=True)
    ujuri_gunaso = models.PositiveIntegerField(default=0, blank=True)
    rbpr = models.PositiveIntegerField(default=0, blank=True)


class NamunaBibaran(FPNBaseModel):
    """model for खाद्य ऐन/नियम बमोजिम संकलित नमुना विवरण"""
    milk = models.PositiveIntegerField(default=0, blank=True)
    oil = models.PositiveIntegerField(default=0, blank=True)
    fruits = models.PositiveIntegerField(default=0, blank=True)
    spice = models.PositiveIntegerField(default=0, blank=True)
    tea = models.PositiveIntegerField(default=0, blank=True)
    salt = models.PositiveIntegerField(default=0, blank=True)
    khadanna = models.PositiveIntegerField(default=0, blank=True)
    water = models.PositiveIntegerField(default=0, blank=True)
    sweets = models.PositiveIntegerField(default=0, blank=True)
    confectionery = models.PositiveIntegerField(default=0, blank=True)
    meat = models.PositiveIntegerField(default=0, blank=True)
    grain = models.PositiveIntegerField(default=0, blank=True)
    others = models.PositiveIntegerField(default=0, blank=True)
    
    def namunabibaran_total_sum(self):
        fields = [
            'milk', 'oil', 'fruits', 'spice', 'tea', 'salt', 'khadanna',
            'water', 'sweets', 'confectionery', 'meat', 'grain', 'others',
        ]
        total_sum = sum(getattr(self, field) for field in fields)
        return total_sum
    
    
class AnugamanBibaran(FPNBaseModel):
    """model for निरीक्षण अनुगमन विवरण"""
    type = models.CharField(max_length=100, choices=commons.ANUGAMAN_CHOICES)
    patak = models.PositiveIntegerField(default=0, blank=True)
    sankhya = models.PositiveIntegerField(default=0, blank=True)
    pragati = models.PositiveIntegerField(default=0, blank=True)
    kaifiyat = models.TextField(default="", blank=True)
    
    def anugamanbibaran_total_sum(self):
        fields = [
            'patak', 'sankhya', 'pragati',
        ]
        total_sum = sum(getattr(self, field) for field in fields)
        return total_sum
    
    
class Logobitaran(FPNBaseModel):
    """model for होटल स्तरीकरण लोगो वितरण सम्बन्धि विवरण"""
    type = models.CharField(max_length=50, choices=commons.LOGO_CHOICES)
    c_pragati = models.PositiveIntegerField(default=0, blank=True)
    h_pragati1 = models.PositiveIntegerField(default=0, blank=True)
    h_pragati2 = models.PositiveIntegerField(default=0, blank=True)
    kaifiyat = models.TextField(default="", blank=True)
    
    def logobitaran_total_sum(self):
        fields = [
            'c_pragati', 'h_pragati1', 'h_pragati2',
        ]
        total_sum = sum(getattr(self, field) for field in fields)
        return total_sum
    
    
class NamunaBisleysan(FPNBaseModel):
    """model for खाद्य तथा दाना नमुना विश्लेषण विवरण"""
    type = models.CharField(max_length=100, choices=commons.TYPES_CHOICES)
    ekai = models.CharField(max_length=10, choices=commons.EKAI_CHOICES, blank=True)
    lakshya = models.PositiveIntegerField(default=0, blank=True)
    pragati1 = models.PositiveIntegerField(default=0, blank=True)
    mahina_pragati = models.PositiveIntegerField(default=0, blank=True)
    sankhya = models.PositiveIntegerField(default=0, blank=True)
    parameter = models.PositiveIntegerField(default=0, blank=True)
    pragati2 = models.PositiveIntegerField(default=0, blank=True)
    pratisat = models.FloatField(default=0, blank=True)
    kaifiyat = models.TextField(default="", blank=True)
    
    def namunabisleysan_total_sum(self):
        fields = [
            'lakshya', 'pragati1', 'mahina_pragati', 'sankhya',
            'parameter', 'pragati2', 'pratisat',
        ]
        total_sum = sum(getattr(self, field) for field in fields)
        return total_sum
    
    
class PrayogsalaBisleysan(FPNBaseModel):
    """model for प्रयोगशाला विश्लेषण प्रतिवेदन सारांश"""
    type = models.CharField(max_length=100, choices=commons.TYPES_CHOICES)
    b_sankhya = models.PositiveIntegerField(default=0, blank=True)
    b_pratikul = models.PositiveIntegerField(default=0, blank=True)
    u_sankhya = models.PositiveIntegerField(default=0, blank=True)
    u_pratikul = models.PositiveIntegerField(default=0, blank=True)
    ay_sankhya = models.PositiveIntegerField(default=0, blank=True)
    ay_pratikul = models.PositiveIntegerField(default=0, blank=True)
    v_sankhya = models.PositiveIntegerField(default=0, blank=True)
    v_pratikul = models.PositiveIntegerField(default=0, blank=True)
    k_sankhya = models.PositiveIntegerField(default=0, blank=True)
    k_pratikul = models.PositiveIntegerField(default=0, blank=True)
    a_sankhya = models.PositiveIntegerField(default=0, blank=True)
    a_pratikul = models.PositiveIntegerField(default=0, blank=True)
    kul_sankhya = models.PositiveIntegerField(default=0, blank=True)
    kul_pratikul = models.PositiveIntegerField(default=0, blank=True)
    sample = models.PositiveIntegerField(default=0, blank=True)
    kaifiyat = models.TextField(default="", blank=True)
    
    def prayogsalabisleysan_total_sum(self):
        fields = [
            'b_sankhya', 'b_pratikul', 'u_sankhya', 'u_pratikul',
            'ay_sankhya', 'ay_pratikul', 'v_sankhya', 'v_pratikul',
            'k_sankhya', 'k_pratikul', 'a_sankhya', 'a_pratikul',
            'kul_sankhya', 'kul_pratikul', 'sample',
        ]
        total_sum = sum(getattr(self, field) for field in fields)
        return total_sum
    
    
class PatraJari(FPNBaseModel):
    """model for खाद्य तथा दाना अनुज्ञा पत्र जारी"""
    milk = models.PositiveIntegerField(default=0, blank=True)
    oil = models.PositiveIntegerField(default=0, blank=True)
    fruits = models.PositiveIntegerField(default=0, blank=True)
    spice = models.PositiveIntegerField(default=0, blank=True)
    tea = models.PositiveIntegerField(default=0, blank=True)
    salt = models.PositiveIntegerField(default=0, blank=True)
    khadanna = models.PositiveIntegerField(default=0, blank=True)
    water = models.PositiveIntegerField(default=0, blank=True)
    sweets = models.PositiveIntegerField(default=0, blank=True)
    confectionery = models.PositiveIntegerField(default=0, blank=True)
    meat = models.PositiveIntegerField(default=0, blank=True)
    grain = models.PositiveIntegerField(default=0, blank=True)
    others = models.PositiveIntegerField(default=0, blank=True)
    
    def patrajari_total_sum(self):
        fields = [
            'milk', 'oil', 'fruits', 'spice',
            'tea', 'salt', 'khadanna', 'water',
            'sweets', 'confectionery', 'meat', 'grain',
            'others',
        ]
        total_sum = sum(getattr(self, field) for field in fields)
        return total_sum
    
    
class PatraNabikaran(FPNBaseModel):
    """model for खाद्य तथा दाना अनुज्ञा पत्र नविकरण"""
    milk = models.PositiveIntegerField(default=0, blank=True)
    oil = models.PositiveIntegerField(default=0, blank=True)
    fruits = models.PositiveIntegerField(default=0, blank=True)
    spice = models.PositiveIntegerField(default=0, blank=True)
    tea = models.PositiveIntegerField(default=0, blank=True)
    salt = models.PositiveIntegerField(default=0, blank=True)
    khadanna = models.PositiveIntegerField(default=0, blank=True)
    water = models.PositiveIntegerField(default=0, blank=True)
    sweets = models.PositiveIntegerField(default=0, blank=True)
    confectionery = models.PositiveIntegerField(default=0, blank=True)
    meat = models.PositiveIntegerField(default=0, blank=True)
    grain = models.PositiveIntegerField(default=0, blank=True)
    others = models.PositiveIntegerField(default=0, blank=True)
    
    def patranabikaran_total_sum(self):
        fields = [
            'milk', 'oil', 'fruits', 'spice',
            'tea', 'salt', 'khadanna', 'water',
            'sweets', 'confectionery', 'meat', 'grain',
            'others',
        ]
        total_sum = sum(getattr(self, field) for field in fields)
        return total_sum
    
    
class UdyogSifaris(FPNBaseModel):
    """model for उद्योग सिफारिस"""
    milk = models.PositiveIntegerField(default=0, blank=True)
    oil = models.PositiveIntegerField(default=0, blank=True)
    fruits = models.PositiveIntegerField(default=0, blank=True)
    spice = models.PositiveIntegerField(default=0, blank=True)
    tea = models.PositiveIntegerField(default=0, blank=True)
    salt = models.PositiveIntegerField(default=0, blank=True)
    khadanna = models.PositiveIntegerField(default=0, blank=True)
    water = models.PositiveIntegerField(default=0, blank=True)
    sweets = models.PositiveIntegerField(default=0, blank=True)
    confectionery = models.PositiveIntegerField(default=0, blank=True)
    meat = models.PositiveIntegerField(default=0, blank=True)
    grain = models.PositiveIntegerField(default=0, blank=True)

templates/report/importexport.html
{% extends 'base/base.html' %}
{% load nepali_month_filter %}
{% load static %}
{% load nepali_month_filter %}
{% block container %}

    <div class="add-heading">
        <h3 class="heading-cm">
            <a href="http://127.0.0.1:5500/html/" class="nav-icon me-2">
                <i class="fa-solid fa-angle-left"></i>
            </a>
            आयात निर्यात गुण प्रमाणिकरण <span class="sub-nav ms-2"> > रिपोर्ट</span>
        </h3>
    </div>

    {% for message in messages %}
        {% if message.tags == "success" %}
            <div class="alert alert-success">{{ message }}</div>
        {% elif message.tags == "error" %}
            <div class="alert alert-danger">{{ message }}</div>
        {% endif %}
    {% endfor %}

    <div class="row mb-4 filter-row filters">
        <div class="row">
            <div class="col-md-5">
                <select id="office" name="status" class="form-select kit-form-control">
                    <option value="all" disabled selected>कार्यालय छान्नुहोस्</option>
                    <option value="Pending">Pending</option>
                    <option value="Verified">Verified</option>
                    <option value="Rejected">Rejected</option>
                </select>
            </div>
            <div class="col-md-3">
                <select id="month" name="status" class="form-select kit-form-control">
                    <option value="all" disabled selected>महिना छान्नुहोस्</option>
                    <option value="बैशाख">बैशाख</option>
                    <option value="जेठ">जेठ</option>
                    <option value="असार">असार</option>
                    <option value="श्रावण">श्रावण</option>
                    <option value="भदौ">भदौ</option>
                    <option value="आश्विन">आश्विन</option>
                    <option value="कार्तिक">कार्तिक</option>
                    <option value="मंसिर">मंसिर</option>
                    <option value="पुष">पुष</option>
                    <option value="माघ">माघ</option>
                    <option value="फाल्गुन">फाल्गुन</option>
                    <option value="चैत्र">चैत्र</option>
                </select>
            </div>
            <div class="col-md-2">
                <button id="filter">फिल्टर</button>
            </div>
            <div class="col-md-2">
                <button id="reset">रिसेट</button>
            </div>
        </div>
    </div>


    <table id="sampleTable" class="table hover-table" style="width:100%">
        <thead>
            <tr>
                <th>क्र. सं.</th>
                {% if request.user.role != 'DE' %}
                    <th>कार्यालय</th>
                {% endif %}
                <th>इकाई</th>
                <th>प्रकार</th>
                <th>चौमासिक प्रगति</th>
                <th>महिनाको प्रगति</th>
                <th>प्रतिकूल नमूना संख्या</th>
                <th>प्रतिकूल पारामिटर</th>
                <th>निर्यात आयात प्रकार</th>
                <th>जम्मा देश</th>
                <th>देशहरुको नाम</th>
                <th>कैफियत</th>
                <th>महिना</th>
                <th>कुल</th>
                <th>Verified</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for d in data %}
            <tr>
                <td>{{forloop.counter}}</td>
                {% if request.user.role != 'DE' %}
                    <td>{{d.created_by.office.name}}</td>
                {% endif %}
                
                <td>{{d.get_ekai_display}}</td>
                <td>{{d.get_type_display}}</td>
                <td>{% quarterly_progress d %}</td>
                <td>{{d.m_pragati}}</td>
                <td>{{d.pratikul_n}}</td>
                <td>{{d.pratikul_p}}</td>
                <td> {{ d.get_broad_type_display }}</td>
                <td>{{d.countries_count }}</td>
                <td>{{d.countries_names }}</td>
                <td>{{d.kaifiyat}}</td>
                <td>{{d.get_related_month_display }}</td>
                <td>{{d.aayatniryat_total_sum}}</td>
                <td>
                    {% if d.is_verified %}
                        <div class="status-box verified">
                            <span class="status-text">Verified</span>
                        </div>
                    {% else %}
                        <div class="status-box not-verified">
                            <span class="status-text">Not Verified</span>
                        </div>
                    {% endif %}
                </td>
                <td>
                    <div class="d-flex kit-action-com">

                        {% if not request.user.role == 'DE' %}
                            <div class="action-btn-pen">
                            <a href="{% url 'import-export-view' id=d.id %}" method="get"><span class="material-symbols-outlined">
                                visibility
                                </span></a>
                            </div>
                        {% endif %}

                        {% if not d.is_verified %}

                            <div class="action-btn-pen">
                                <a href="{% url 'importexport-edit' id=d.id %}" method="put"><span class="material-symbols-outlined">
                                        edit
                                        </span></a>
                                </div>

                            <div class="action-btn-pen dlt-btn">
                                <a href="" method="put" data-bs-toggle="modal" data-bs-target="#staticBackdrop"><span class="material-symbols-outlined ">
                                    delete
                                    </span></a>
                                </div>

                                <div class="action-btn-pen dlt-btn">
                                    <a href="" method="put" data-bs-toggle="modal" data-bs-target="#report{{d.id}}"><span class="material-symbols-outlined">
                                        report
                                        </span></a>
                                    </div>
                        
                        {% endif %}

                        <form class="action-btn-dlt" action="{% url 'import-export-delete' id=d.id %}" method="post">
                            {% csrf_token %}

                            <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered confirmation-modal">
                                    <div class="modal-content">
                                
                                    <div class="modal-body delete-body">
                                    <span class="material-symbols-outlined delete-icon">cancel</span>
                                        <h3 class="mb-2">Are you sure ?</h3>
                                        <p>Do you really want to delete this certificate ?<br>
                                    </p></div>
                                    <div class="modal-footer d-flex justify-content-center">
                                    <div class="row d-flex">
                                        <div class="col-md-12">
                                            <button type="button" class="btn cancel-btn" data-bs-dismiss="modal">Cancel</button>
                                            <button type="submit" class="btn btn-danger delete-btn">Delete</button>
                                        </div>
                                    </div>
                                        
                                    </div>
                                    </div>
                                </div>
                            </div>
                        </form>

                        <div class="modal fade" id="report{{d.id}}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered confirmation-modal">
                                <div class="modal-content">
                            
                                <div class="modal-body delete-body">
                                    <h3 class="mb-2">Remarks</h3>
                                    {% if d.remarks %}
                                        <p>{{ d.remarks }}</p>
                                    {% else %}
                                        <p>No remarks available</p>
                                    {% endif %}
                                </p></div>
                                <div class="modal-footer d-flex justify-content-center">
                                <div class="row d-flex">
                                    <div class="col-md-12">
                                        <button type="button" class="btn cancel-btn" data-bs-dismiss="modal">Cancel</button>
                                    </div>
                                </div>
                                    
                                </div>
                                </div>
                            </div>
                        </div>


                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
        <td>Total:</td>
        {% if request.user.role != 'DE' %}
            <td></td>
        {% endif %}
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>{{total_sum}}</td>
        <td></td>
        <td></td>
    </table>

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.2/moment.min.js"></script>
    <script src="https://cdn.datatables.net/datetime/1.4.1/js/dataTables.dateTime.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.print.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>

    <script src="../datepicker/nepali-date-picker.min.js"></script>

    <script src="../../js/script.js"></script>



    <script>
        $(document).ready(function () {
            var table = $('#sampleTable').DataTable({
                dom: 'Bfrtip',
                buttons: [{
                    extend: 'copy',
                    exportOptions: {
                        columns: [0, 1, 2, 3]
                    }
                },
                {
                    extend: 'csv',
                    exportOptions: {
                        columns: [0, 1, 2, 3]
                    }
                },
                {
                    extend: 'excel',
                    exportOptions: {
                        columns: [0, 1, 2, 3]
                    }
                },
                {
                    extend: 'pdf',
                    exportOptions: {
                        columns: [0, 1, 2, 3]
                    }
                },
                {
                    extend: 'print',
                    exportOptions: {
                        columns: [0, 1, 2, 3]
                    }
                }
                ],
                columnDefs: [
                    {
                        targets: -1,
                        visible: true,
                    }
                ]
            });


            $('#office').on('change', function () {
                var type = $(this).val();
                table.columns(12).search(type).draw();
            });
            $('#month').on('change', function () {
                var type = $(this).val();
                table.columns(11).search(type).draw();
            });


            $('#reset').on('click', function () {
                $('#office').val('all').trigger('change.select2');
                $('#month').val('all');

                table.columns().search('').draw();
                table.draw();
            });

        });
    </script>

{% endblock %}